### PR TITLE
fix linting errors

### PR DESCRIPTION
**Pull request by skb1129**
### Checks

- [x] I have read the contribution guidelines regarding Pull Requests here: https://git.io/JJ0Pg

### CODE REVIEW

**Review by jsamr — APPROVED** [review]

**Comment by skb1129** [comment]
@jsamr would you be able to create a new NPM release after merging this?

**Comment by jsamr** [comment]
@skb1129 I cannot promise anything, but will consider releasing when I find some time off.

**Comment by stevekuznetsov** [comment]
@jsamr if you do end up having some time, it would be extremely appreciated if you could release a new version for this!

**Comment by tmeduho** [comment]
Thanks @jsamr!

**Comment by fjorty** [comment]
@skb1129 Thank you for the fix! 
@jsamr The recent updates and fixes have been incredibly helpful, and having them available in the latest npm release would be greatly appreciated. Thank you for your hard work and dedication to maintaining this package!

**Comment by gmontemayor1987** [comment]
Thank you guys for the fix, I would also love a release

**Comment by tmeduho** [comment]
@jsamr what would it take to get a new release soon? 🙏

**Pull request merged**
