### PR TITLE
fix: Add xxx-large for ABSOLUTE_FONT_SIZE

### PR DESCRIPTION
**Pull request by maltoze**
### Checks

- [x] I have read the contribution guidelines regarding Pull Requests here: https://git.io/JJ0Pg 

### Description
Add `xxx-large` for `ABSOLUTE_FONT_SIZE`
See the documents: 
https://drafts.csswg.org/css-fonts/#absolute-size-mapping
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Values

### CODE REVIEW

**Comment by jsamr** [comment]
@maltoze `xxx-large` is not part of the CSS standard. See https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#absolute-size-value

**Comment by qwertychouskie** [comment]
> @maltoze `xxx-large` is not part of the CSS standard. See [w3.org/TR/2018/REC-css-fonts-3-20180920#absolute-size-value](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#absolute-size-value)

It exists in newer versions of the spec: https://www.w3.org/TR/css-fonts-4/

Perhaps this PR should be re-opened?

**Comment by jsamr** [comment]
@maltoze Are you able to rebase, or shall we open a new PR?

**Comment by maltoze** [comment]
please open a new PR.

**Pull request closed without merging**
