### PR TITLE
🚀 Foundry release

### PR DESCRIPTION
**Pull request by jsamr**
<p align="center">
<strong>Foundry Status</strong><br/>

<br/>
<a href="https://github.com/meliorence/react-native-render-html/issues/430">Check the announcement thread</a>
</p>

## Remaining work before stable release

**Feature Parity (v4)**

- [x] Support `ignoredTags` (renamed `ignoredDomTags`)
- [x] Support `ignoreNodesFunction` (renamed `ignoreDomNode`)
- [x] Support `alterNode` (moved to `domVisitors.onElement`, tamper directly the node reference and use [domutils](https://github.com/fb55/domutils) to insert, delete children)
- [x] Support `alterChildren` (moved to `domVisitors.onElement`, tamper with children via [domutils](https://github.com/fb55/domutils))
- [x] Support `alterData` (moved to `domVisitors.onText`; tamper directly the node reference `text` field)
- [x] Support `renderersProps`
- [x] Support `ignoredStyles` (BREAKING: names should be camelCased.)
- [x] Support `allowedStyles` (BREAKING: names should be camelCased.)
- [x] Support `emSize`
- [x] Support `nodeIndex` and `parent` via `tnode`
- [x] Support an equivalent of `listsPrefixesRenderers` → `customListStyleSpecs`

**Feature Parity (v5)**

- [x] replace `computeImagesMaxWidth` with `computeEmbeddedMaxWidth`
- [x] support for htmlParserOptions
- [x] provide a podspec file
- [x] defaultTextProps
- [x] replace `html` and `uri` with `source` (supports `method`, `body` and `headers`)
- [x] `WebView` and `defaultWebViewProps` props
- [x] `domNodeToHTMLString` util

**Fixes**
- [x] Fix bullet sizes in ul + fix squares on iOS
- [x] Fix spacing in ol
- [x] unsupported tags should not break the inline context
- [x] Handle negative values in "collapse margins"
- [x] Fix ordered list elements alignment on iOS
- [x] Fix lists issues, https://github.com/meliorence/react-native-render-html/issues/430#issuecomment-783053463

**New Features**
- [x] Reuse special internal renderers logic (img, a, ul and ol) in custom renderers with `useInternalRenderer`. 
- [x] Minimal renderer for tables. This renderer doesn't follow the CSS display: table, table-row and table-cell, because the display engine of react native only supports the flex display algorithm. To have a fully compliant table renderer, you can still use the @native-html/table-plugin package. 
- [x] `defaultViewProps`
- [x] Access `DocumentMetadata` from any component (an object containing meta information of the document, such as lang, baseUrl, ...etc) with `useDocumentMetadata` hook, and from the controlling component with `onDocumentMetadataLoaded` prop.
- [x] Support `baseUrl` for `RenderHTMLSourceInline` sources
- [x] Provide URL normalization logic to users with `DocumentMetadata`. This helps normalize relative `src` and `href`s (`useNormalizedUrl` hook).
- [x] `TRenderEngineProvider` component to share one engine instance across multiple `RenderHTML` instances.
- [x] Implement the "marker model". Markers are special properties attached to a node which are inherited by all descendant nodes. For example, we could imagine adding blue borders to images which have an anchor parent. To check that we have an anchor parent, we will just need to test `markers.anchor === true` from the `markers` prop. You can also set custom markers with `setMarkersForTNode` prop.

**Postponed**

- 🗙 90%+ branch test coverage → During beta testing
- 🗙 Evaluate the cost of implementing CSS compliant "em" unit (current implementation doesn't follow the standard and is equivalent to rem).

**Doc**

- [x] Update README
- [x] (Maybe) create documentation website
- [x] New Discovery App (WIP) ; this enhanced demo app will also act as a guide to learn the fundamentals.
- [x]  Migration guide

**Tests**

- [x] port all tests from v5
- [x] fix a handful of failing tests from v5

**Modules**

- [x] Extract iframe to a new package
- [x] Create a compatible release of @native-html/table-plugin
- [x] Create a compatible release of @native-html/iframe-plugin
- 🗙 ~~compat module to ease the transition~~ cancelled in favor of migration guide

## Fixes

- Unrecognized styles crash the app (#369, #432, #418)
- Missing inheritable styles (#344)
- List prefixes styles (#151, #414, #144)
- Whitespace collapsing (#118)
- Custom Text props (#94, #360)
- cite tags (#420)
- Missing text output (#156)

### New props

- `idsStyles` property (similar to classesStyles);
- Support font selection (`systemFonts` and `fallbackFonts` props), see demo.
- `enableUserAgentStyles` (true by default, the "browser" styles);
- `enableCSSInlineParsing` (true by default)
- `enableExperimentalMarginCollapsing` to comply with the margin collapsing CSS standard (experimental, only work on adjacent blocks, and doesn't work with percent units), see demo;
- `extendDefaultRenderer` utility to tamper with the element model of a tag (see "Model Tampering" in the demo, which allows inline images!).
- `customListStyleSpecs` to create arbitrary list counter styles.
- `renderersProps` now supports renderer-specific fields. For example, `renderersProps.a.onPress` replaces `onLinkPress` prop.
- `renderersProps.(ol|ul).enableExperimentalRtl` to reverse the display order of list markers and content when either dir attribute or direction CSS property are set to `"rtl"`.

### Elements

- Support descriptions lists (`<dl>`)
- Support `<ins>`, `<del>`
- ... and many more! [The full list is available in @native-html/transient-render-tree](https://github.com/native-html/core/blob/master/packages/transient-render-engine/src/model/defaultHTMLElementModels.ts).

### CSS

- Complex style inheritance following closely CSS specificity;
- White space collapsing! (#118) You can actually control this behavior (*pre* or *normal*) with a new special `whiteSpace` style property, or inline `white-space: xx;` see demo;
- Support for the inline [`list-style-type` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type)! Also available in passed styles (tagsStyles...). Currently works with *disc, circle, square, decimal, lower-alpha; upper-alpha*. It currently only works with `li` and `ul` tags, see demo.
- Extended support of special CSS units (e.g. 'thin' for border-width).
- Extended support for basic CSS units (all absolute sizes such as pt, in, cm ... + ex).

### Renderer API

- Powerful new flexible API based on the [transient render engine!](https://github.com/native-html/core/tree/master/packages/transient-render-engine) ! Renderers are now components and not functions.
- Custom renderers can easily reuse internal renderers, including children rendering logic. In addition to arguments that where available in the previous API, have access to the internal renderer component and props by using `useInternalRenderer` hook, to which you can pass ViewProps or TextProps, depending on the tnode, along with specific props for this renderer. This default renderer also supports `onPress` prop, so any renderer can be super easily configured as interactive!
- Renderers are now bound to an element model, which characterizes how the element will be translated by the transient render engine (`contentModel`), what are the "user agent" styles for this tag (`mixedUAStyles`) and how to derive conditional user agent styles from attributes (`getUADerivedStyleFromAttributes`). There are some advanced options, such as `isOpaque`, which allows access to the children DOM tree from the TNode, especially useful for SVG and other special markups.
Most of the time, you don't have to care about it, and just use the default model for this tag exported in `defaultHTMLElementModels`. It is yet a powerful feature which lets you put the hands on the engine!
- Thanks to the separation between renderers and their content model, images can now be displayed inline (#428)

#### Example of Custom Interactive

```tsx
import React, { useCallback, useState } from 'react';
import {
  BlockRenderer,
  defaultHTMLElementModels,
  HTMLContentModel
} from 'react-native-render-html';
import { Text } from 'react-native';
import { Snackbar } from 'react-native-paper';

const ButtonRenderer: BlockRenderer = function ({
  TDefaultRenderer,
  ...props
}) {
  const [isVisible, setIsVisible] = useState(false);
  const onPress = useCallback(() => {
    setIsVisible(true);
  }, []);
  return (
    <>
      <TDefaultRenderer {...props} onPress={onPress} />
      <Snackbar
        duration={1200}
        visible={isVisible}
        onDismiss={() => setIsVisible(false)}>
        <Text>Button has been clicked!</Text>
      </Snackbar>
    </>
  );
};

// We need to extend the button HTMLElementModel because its
// default content model is HTMLContentModel.none. This is true
// for any interactive element.
ButtonRenderer.model = defaultHTMLElementModels.button.extend({
  contentModel: HTMLContentModel.block,
  mixedUAStyles: {
    textAlign: 'center',
    padding: 10,
    backgroundColor: 'rgba(125, 125, 125, 0.5)'
  }
});

const renderers = {
  button: ButtonRenderer
};

export default renderers;
```

#### Example of "Children Tampering"

Below is an example where our custom article render will inject advertisement below the second and fourth children:

```tsx
import React from 'react';
import {
  BlockRenderer,
  defaultHTMLElementModels,
  useTNodeChildrenProps,
  TChildrenRenderer
} from 'react-native-render-html';
import { View, Text } from 'react-native';
import { SnippetDeclaration } from '../types';

const html = `
<article>
  <p>Paragraph 1</p>
  <p>Paragraph 2</p>
  <p>Paragraph 3</p>
  <p>Paragraph 4</p>
  <p>Paragraph 5</p>
</article>`;

function AdComponent() {
  return (
    <View
      style={{ backgroundColor: 'purple', padding: 10, alignSelf: 'stretch' }}>
      <Text style={{ color: 'white' }}>I am an AD!</Text>
    </View>
  );
}

const ArticleRenderer: BlockRenderer = function ArticleRenderer(props) {
  const { tnode, TDefaultRenderer, ...defaultRendererProps } = props;
  const tchildrenProps = useTNodeChildrenProps(props);
  const firstChildrenChunk = tnode.children.slice(0, 2);
  const secondChildrenChunk = tnode.children.slice(2, 4);
  const thirdChildrenChunk = tnode.children.slice(4, 5);
  return (
    <TDefaultRenderer tnode={tnode} {...defaultRendererProps}>
      <TChildrenRenderer {...tchildrenProps} tchildren={firstChildrenChunk} />
      {firstChildrenChunk.length === 2 ? <AdComponent /> : null}
      <TChildrenRenderer {...tchildrenProps} tchildren={secondChildrenChunk} />
      {secondChildrenChunk.length === 2 ? <AdComponent /> : null}
      <TChildrenRenderer {...tchildrenProps} tchildren={thirdChildrenChunk} />
    </TDefaultRenderer>
  );
};

ArticleRenderer.model = defaultHTMLElementModels.article;

const renderers = {
  article: ArticleRenderer
}

export default renderers;
```

will render this html snippet:

```html
<article>
  <p>Paragraph 1</p>
  <p>Paragraph 2</p>
  <p>Paragraph 3</p>
  <p>Paragraph 4</p>
  <p>Paragraph 5</p>
</article>
```
like this

## Removed props

- `customWrapper` and `containerStyle`
-  `onParsed`
- `staticContentMaxWidth`
- `ignoreNodesFunction`
- `ptSize`

### CODE REVIEW

**Comment by bmanturner** [comment]
`baseStyle` isn't applying styles to text elements. There are no example snippets of this functionality either. `p` and `span` also can't be targeted by `tagsStyles` for some reason

**Comment by jsamr** [comment]
> `baseStyle` isn't applying styles to text elements. There are no example snippets of this functionality either. `p` and `span` also can't be targeted by `tagsStyles` for some reason

If you're willing to provide a Snack with the latest foundry pre-release with an example of the issues you're facing, I'll be happy to investigate.

**Comment by bmanturner** [comment]
I apologize for not knowing how to do that. Use `baseStyle` to try to change the color or size of the font and you'll see what I'm talking about.

```
const html = '<p>MAKE ME BIG</p>';

return <HTML source={{ html }} baseStyle={{ fontSize: 24 }} />;
```

Does not work.

**Comment by jsamr** [comment]
> baseStyle={{ fontSize: 24 }}

Works for me, see https://snack.expo.io/@jsamr/bmanturner-report

**Comment by bmanturner** [comment]
Turns out the hot code refresh on expo wasn't loading the changes. I had to reload the entire app to see the changes. Sorry for wasting your time. I appreciate your prompt attention. Have a nice day

**Comment by jsamr** [comment]
@bmanturner No worries, I'm glad it worked out well. RN developing experience can be frustrating regarding cache! Next time, I recommend you use our Discord channel to request for help :-)

**Comment by bmanturner** [comment]
I don't see a link to a discord on the readme?

**Comment by jsamr** [comment]
@bmanturner Check the badges!

**Pull request merged**
